### ISSUE TITLE
pre-model cannot be downloaded

### ISSUE THREAD

**Issue by xuancaiqisehua** [FrePainter/code#1]
Has the model download link expired? I am unable to download the model.

**Comment by FrePainter** [comment]
I apologize for the late response. I have confirmed that the download link for the checkpoint is working properly.
I will provide you with an additional download link, so please try using this [link](https://drive.google.com/file/d/1E9v-UadS4-aJEnSvrVh6vLINa3v67uXF/view?usp=sharing).
URL: [https://drive.google.com/file/d/1E9v-UadS4-aJEnSvrVh6vLINa3v67uXF/view?usp=sharing](https://drive.google.com/file/d/1E9v-UadS4-aJEnSvrVh6vLINa3v67uXF/view?usp=sharing)

**Comment by xuancaiqisehua** [comment]
> I apologize for the late response. I have confirmed that the download link for the checkpoint is working properly. I will provide you with an additional download link, so please try using this [link](https://drive.google.com/file/d/1E9v-UadS4-aJEnSvrVh6vLINa3v67uXF/view?usp=sharing). URL: https://drive.google.com/file/d/1E9v-UadS4-aJEnSvrVh6vLINa3v67uXF/view?usp=sharing

Okay, thank you very much, I'll try it again

**Comment by l6chen** [comment]
Hi, thanks for your work. But are you sure the checkpoint is the model whose results are shown on your demo webpage? It seems that there is a little difference between the inference result from my local environment and that on the website. I got the inference result as:
`MODEL_NAME=pt_rd_80_ft_ub_mrv2 
DATA_DIR=../datasets/vctk_test/p360_418.wav 
OUTPUT_DIR=./logs/results/ssr_vckt
EXT=wav
sh inference.sh $MODEL_NAME $DATA_DIR $OUTPUT_DIR $EXT`
where the wav file is directly downloaded from your demo webpage.
My inference result sounds a little noisy and not clear enough as yours.
