### ISSUE TITLE
inference results different from demo's

### ISSUE THREAD

**Issue by l6chen** [FrePainter/code#2]
Hi, thanks for your work. But are you sure the checkpoint is the model whose results are shown on your demo webpage? It seems that there is a little difference between the inference result from my local environment and that on the website. I got the inference result as:
`MODEL_NAME=pt_rd_80_ft_ub_mrv2  DATA_DIR=../datasets/vctk_test/p360_418.wav  OUTPUT_DIR=./logs/results/ssr_vckt EXT=wav sh inference.sh $MODEL_NAME $DATA_DIR $OUTPUT_DIR $EXT`
where the wav file is directly downloaded from your demo webpage.
My inference result sounds a little noisy and not clear enough as yours.

**Comment by sb-kim-prml** [comment]
Hi, thanks for your interest in our work.

We have noticed a decrease in audio quality during inference trough the 'inference.sh (inference_from_audio.py)' script. Consequently, we have made improvements to the 'inference_from_audio.py' and  'data_utils.py' scripts. We suggest updating both files to their improved versions and running the inference again. 

The checkpoint differs from the one on the demo page, but it is the latest checkpoint with better performance.

**Comment by sb-kim-prml** [comment]
Hi, thanks for your interest in our work.

We have noticed a decrease in audio quality during inference trough the 'inference.sh (inference_from_audio.py)' script. Consequently, we have made improvements to the 'inference_from_audio.py' and 'data_utils.py' scripts. We suggest updating both files to their improved versions and running the inference again.
```
MODEL_NAME=pt_rd_80_ft_ub_mrv2
DATA_DIR=[Directory or audio file]
OUTPUT_DIR=[output directory]
EXT=wav
CUDA_VISIBLE_DEVICES=0,1 python inference_from_audio.py \
  -m $MODEL_NAME -d $DATA_DIR -o $OUTPUT_DIR -e $EXT
 ```

The checkpoint differs from the one on the demo page, but it is the latest checkpoint with better performance.

**Comment by l6chen** [comment]
OK, I update my code and rerun the testcases. The audio quality is better.
But there are two bugs:
1. from mel_processing import mel_spectrogram_torch should be added there:
https://github.com/FrePainter/code/blob/ff3a3fcc0e0a3e0bea2a73f7ef52a5e26ad4ac70/data_utils.py#L11
2. the length of src and pred may diff there:
https://github.com/FrePainter/code/blob/ff3a3fcc0e0a3e0bea2a73f7ef52a5e26ad4ac70/post_processing.py#L16

**Comment by sb-kim-prml** [comment]
Thank you for pointing out that we missed.

We have added "from mel_processing import mel_spectrogram_torch" to 'data_utils.py'. 
Additionally, to address the second case, we have added padding to match the hop size in 'data_utils.py'.

https://github.com/FrePainter/code/blob/206f328b004b732fefaf4a062dd4b76fb5feb637/data_utils.py#L363-L364
